name:  Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3add trivy file scan stage
      - name: Install Trivy
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh

      - name: Run Trivy scan
        run: |
          trivy fs . # Scan the current directory. Adjust the path or options as needed  
