name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  install-trivy:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Verify Trivy installation
        run: trivy --version

  trivy-scan:
    runs-on: ubuntu-latest
    needs: install-trivy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trivy scan
        run: |
          trivy fs --exit-code 1 --no-progress .
        continue-on-error: true
        working-directory: ./src/adservice/

  gradle-build:
  runs-on: ubuntu-latest
  needs: checkout

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and test with Gradle using Docker
      run: |
        docker run --rm \
          -v $(pwd)/src/adservice:/workspace \
          -w /workspace \
          eclipse-temurin:19.0.1_10-jre-alpine \
          sh -c "chmod +x ./gradlew && ./gradlew build && ./gradlew test"

  docker-build:
    runs-on: ubuntu-latest
    needs: gradle-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app-image:latest .
        working-directory: ./src/adservice/
