name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  install-trivy:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb
          working-directory: ./src/adservice/.

  trivy-scan:
    runs-on: ubuntu-latest
    needs: install-trivy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trivy scan
        run: |
          trivy fs --exit-code 1 --no-progress .
        continue-on-error: true
        working-directory: ./src/adservice/.
