name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  install-trivy:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb
          sudo apt-get install -f  # Fix dependencies
          trivy --version

  trivy-scan-adservice:
    runs-on: ubuntu-latest
    needs: install-trivy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trivy scan for adservice
        run: |
          trivy fs --exit-code 1 --no-progress .
        continue-on-error: true
        working-directory: ./src/adservice/

  dotnet-build-cartservice:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build and test with .NET for cartservice
        run: |
          cd src/cartservice
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal

  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in context directory
        run: ls -la ./src/cartservice/src/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sharuelement/newcart:latest
          context: ./src/cartservice/src/
